# Generated by Django 4.2.25 on 2025-10-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("org", "club"),
                    ("moderator", "Moderator"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
