# Generated by Django 4.2.25 on 2025-11-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_role'),
        ('profiles', '0005_alter_profile_role'),
    ]

    operations = [
    ]
