# Generated by Django 4.2.25 on 2025-11-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_0003_alter_profile_role_0005_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.CharField(blank=True, choices=[('korean', 'Korean'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('american', 'American'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('halal', 'Halal'), ('vegan', 'Vegan'), ('bbq', 'BBQ'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
