# Generated by Django 4.2.25 on 2025-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferences',
            field=models.CharField(choices=[('korean', 'Korean'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('american', 'American'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('halal', 'Halal'), ('vegan', 'Vegan'), ('bbq', 'BBQ'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('other', 'Other')], default='Korean', max_length=20),
        ),
    ]
