# Generated by Django 4.2.25 on 2025-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_preferences_profile_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.CharField(blank=True, choices=[('korean', 'Korean'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('american', 'American'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('halal', 'Halal'), ('vegan', 'Vegan'), ('bbq', 'BBQ'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
