# Generated by Django 4.2.25 on 2025-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_cuisine_alter_post_cuisine'),
        ('profiles', '0010_remove_profile_preferences_profile_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='posting.cuisine'),
        ),
    ]
