# Generated by Django 4.2.25 on 2025-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_preferences_profile_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('org', 'club'), ('moderator', 'Moderator')], default=None, max_length=20),
        ),
    ]
