# Generated by Django 4.2.25 on 2025-11-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("org", "club"),
                    ("moderator", "Moderator"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
