# Generated by Django 4.2.25 on 2025-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
