# Generated by Django 4.2.25 on 2025-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_allergen'),
        ('profiles', '0014_profile_has_seen_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='posting.allergen'),
        ),
    ]
