# Generated by Django 4.2.25 on 2025-11-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_profile_allergens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
