# Generated by Django 4.2.25 on 2025-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_profile_bio_profile_major_alter_profile_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="major",
            field=models.TextField(blank=True, null=True),
        ),
    ]
