# Generated by Django 4.2.25 on 2025-11-03 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('event_description', models.TextField()),
                ('cuisine', models.CharField(choices=[('korean', 'Korean'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('american', 'American'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('indian', 'Indian'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese'), ('halal', 'Halal'), ('vegan', 'Vegan'), ('bbq', 'BBQ'), ('seafood', 'Seafood'), ('dessert', 'Dessert'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posting.models.event_image_upload_to)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
