# Generated by Django 4.2.25 on 2025-11-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_preferences_profile_preferences'),
        ('posting', '0002_cuisinetag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuisineTag',
        ),
    ]
