# Generated by Django 4.2.25 on 2025-11-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_delete_cuisinetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posting.cuisine'),
        ),
    ]
