# Generated by Django 4.2.25 on 2025-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
