# Generated by Django 4.2.25 on 2025-11-14 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0005_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_users',
            field=models.ManyToManyField(blank=True, related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
