# Generated by Django 4.2.25 on 2025-11-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0005_allergen'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerThank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks_received', to=settings.AUTH_USER_MODEL)),
                ('thanker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('thanker', 'organizer')},
            },
        ),
    ]
