# Generated by Django 4.2.25 on 2025-11-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posting", "0006_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
