# Generated by Django 4.2.25 on 2025-11-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0006_organizerthank"),
        ("posting", "0006_post_is_deleted"),
        ("posting", "0006_post_publish_at_post_status"),
        ("posting", "0006_post_read_users"),
        ("posting", "0007_post_qr_code_image"),
    ]

    operations = []
