# Generated by Django 4.2.25 on 2025-11-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posting", "0009_location_post_location_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pickup_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="When will you stop giving out food? (Leave empty if no specific deadline)",
                null=True,
            ),
        ),
    ]
