# Generated by Django 4.2.25 on 2025-11-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0011_location_post_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('post', 'reporter'), name='unique_report_per_user_per_post'),
        ),
    ]
