# Generated by Django 4.2.25 on 2025-11-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0012_report_unique_report_per_user_per_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
