# Generated by Django 4.2.25 on 2025-11-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_seen_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
