# Generated by Django 4.2.25 on 2025-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posting", "0015_rsvp_is_seen_by_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("friends", "Friends Only")],
                default="public",
                help_text="Who can see this post? Public or Friends Only.",
                max_length=20,
            ),
        ),
    ]
