# Generated by Django 4.2.27 on 2025-12-09 13:19

from django.db import migrations


def seed_allergens(apps, schema_editor):
    """Seed the database with common food allergens."""
    Allergen = apps.get_model('posting', 'Allergen')
    
    common_allergens = [
        'Peanuts',
        'Tree Nuts',
        'Dairy',
        'Eggs',
        'Gluten',
        'Soy',
        'Shellfish',
        'Fish',
        'Sesame',
    ]
    
    for allergen_name in common_allergens:
        Allergen.objects.get_or_create(name=allergen_name)


def reverse_seed_allergens(apps, schema_editor):
    """Remove seeded allergens (optional reverse operation)."""
    Allergen = apps.get_model('posting', 'Allergen')
    Allergen.objects.filter(name__in=[
        'Peanuts', 'Tree Nuts', 'Dairy', 'Eggs', 
        'Gluten', 'Soy', 'Shellfish', 'Fish', 'Sesame'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0016_post_visibility'),
    ]

    operations = [
        migrations.RunPython(seed_allergens, reverse_seed_allergens),
    ]
