# Generated by Django 4.2.25 on 2025-10-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
