# Generated by Django 4.2.25 on 2025-11-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
