# Generated by Django 4.2.25 on 2025-11-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_is_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_group',
        ),
    ]
