# Generated by Django 4.2.25 on 2025-11-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='dm_key',
            field=models.CharField(blank=True, help_text="Canonical key for 1:1 DMs, e.g. '3:7'. Null for group chats.", max_length=50, null=True, unique=True),
        ),
    ]
