"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
try:
    import django_heroku
except ImportError:
    django_heroku = None

from pathlib import Path
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8bis&y=06s^*mr9f!pc#go*w!xilx(sa4op@!do_8%s44(nn!v"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'swe-b-27-0f4424ee120f.herokuapp.com',
    '127.0.0.1',
    'localhost',


]

CSRF_TRUSTED_ORIGINS = [
    'https://swe-b-27-0f4424ee120f.herokuapp.com',
    'http://localhost:8000',

]



# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "loginpage",
    "landingpage",
    "profiles.apps.ProfilesConfig",
    "userprivileges",
    "chat",
    "Friendslist",
    "storages",
    "posting",

]

#AWS settings
AWS_ACCESS_KEY_ID = 'AKIAT4WRC67XVTE5SVOC'
AWS_SECRET_ACCESS_KEY = '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'

AWS_STORAGE_BUCKET_NAME = 'swe-b-27-profile-pics'

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_S3_FILE_OVERWRITE = False

STORAGES = {
    #media file (image) management
    'default': {
        "BACKEND": 'storages.backends.s3boto3.S3Boto3Storage',
    },

    #CSS and JS file management
    "staticfiles":{
        "BACKEND": 'storages.backends.s3boto3.S3Boto3Storage',
    },
}


SITE_ID = 1
# Create accounts automatically from Google data
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_URL = "/accounts/google/login/"
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_VERIFICATION = "none"

LOGIN_REDIRECT_URL = reverse_lazy("post_login_redirect")

ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = reverse_lazy("landingpage")

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_ADAPTER = "loginpage.adapters.MySocialAccountAdapter"



AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"prompt": "select_account"},
    }
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    'allauth.account.middleware.AccountMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]



ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], #add this for templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'chat.context_processors.unread_messages',
                "Friendslist.context_processors.pending_friend_requests_count"
            ],
        },
    },
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'chat.context_processors.pending_friend_requests_count',
]

WSGI_APPLICATION = "myproject.wsgi.application"





# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


#STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Activate Django-Heroku (auto database + static config)
try:
    if 'HEROKU' in os.environ:
        django_heroku.settings(locals())
except ImportError:
    pass
