# Generated by Django 4.2.25 on 2025-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flaggedcontent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved (No Action)"),
                    ("deleted", "Content Deleted"),
                    ("dismissed", "Dismissed"),
                    ("edited", "Content Edited"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
