# Generated by Django 4.2.25 on 2025-11-15 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0002_alter_flaggedcontent_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for suspending this user"),
                ),
                ("suspended_at", models.DateTimeField(auto_now_add=True)),
                (
                    "suspended_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for permanent suspension",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this suspension is currently active",
                    ),
                ),
                ("reinstated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reinstatement_notes",
                    models.TextField(
                        blank=True, help_text="Notes about why user was reinstated"
                    ),
                ),
                (
                    "reinstated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_reinstated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Suspension",
                "verbose_name_plural": "User Suspensions",
                "ordering": ["-suspended_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="moderation__user_id_25511c_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-suspended_at"],
                        name="moderation__is_acti_bb49d8_idx",
                    ),
                ],
            },
        ),
    ]
