# Generated by Django 4.2.25 on 2025-12-08 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("moderation", "0003_usersuspension"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeratorNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flagged_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="moderation.flaggedcontent",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator Notification",
                "verbose_name_plural": "Moderator Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["moderator", "is_read"],
                        name="moderation__moderat_a5af4d_idx",
                    ),
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="moderation__is_read_ae329a_idx",
                    ),
                ],
                "unique_together": {("moderator", "flagged_content")},
            },
        ),
        migrations.CreateModel(
            name="ModeratorActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("flag_created", "Flag Created"),
                            ("content_deleted", "Content Deleted"),
                            ("content_edited", "Content Edited"),
                            ("user_suspended", "User Suspended"),
                            ("user_reinstated", "User Reinstated"),
                            ("post_created", "Post Created"),
                            ("post_edited", "Post Edited"),
                            ("post_deleted", "Post Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(help_text="Description of the action"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this activity is related to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="The user who performed this action (moderator or organization user)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="moderation__organiz_49ce3c_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="moderation__action__c650a0_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="moderation__content_dda8d6_idx",
                    ),
                ],
            },
        ),
    ]
